# Site settings
title: Tournament Schema
description: "API and schema documentation for describing tournaments."
baseurl: ""
url: "http://schema.quizbowl.technology"
username: "quizbowl"
defaults:
  -
    scope:
      path: ""
    values:
      show_in_nav: true

# Build settings
markdown: kramdown
permalink: pretty
